<template>
    <div>
        <div class="buttons">
            <a
                class="button"
                href="https://vee-validate.logaretm.com/v3"
                target="_blank">
                Website
            </a>
            <a
                class="button"
                href="https://vee-validate.logaretm.com/v3/guide/basics.html"
                target="_blank">
                Docs
            </a>
            <a
                class="button"
                href="https://vee-validate.logaretm.com/v3/guide/3rd-party-libraries.html#buefy"
                target="_blank">
                Example
            </a>
        </div>
    </div>
</template>
